// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WasteGlassApi.Data;

#nullable disable

namespace WasteGlassApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WasteGlassApi.Models.CollectionRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ClearKg")
                        .HasColumnType("double precision");

                    b.Property<double>("ColouredKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Synced")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("CollectionRecords");
                });

            modelBuilder.Entity("WasteGlassApi.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BarcodeRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ExpectedKg")
                        .HasColumnType("double precision");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "12 Galle Rd, Colombo 03",
                            BarcodeRef = "SUP001",
                            ExpectedKg = 45.0,
                            Latitude = 6.9146999999999998,
                            Longitude = 79.858400000000003,
                            Name = "Colombo Glass Depot",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Address = "34 Beach Rd, Negombo",
                            BarcodeRef = "SUP002",
                            ExpectedKg = 30.0,
                            Latitude = 7.2096,
                            Longitude = 79.8369,
                            Name = "Negombo Recycle Hub",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Address = "78 Kandy Rd, Ja-Ela",
                            BarcodeRef = "SUP003",
                            ExpectedKg = 60.0,
                            Latitude = 7.0731999999999999,
                            Longitude = 79.891300000000001,
                            Name = "Ja-Ela Glass Store",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 4,
                            Address = "22 Main St, Wattala",
                            BarcodeRef = "SUP004",
                            ExpectedKg = 25.0,
                            Latitude = 6.9897,
                            Longitude = 79.889099999999999,
                            Name = "Wattala Collection Point",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 5,
                            Address = "56 Kelani Rd, Kelaniya",
                            BarcodeRef = "SUP005",
                            ExpectedKg = 40.0,
                            Latitude = 6.9550000000000001,
                            Longitude = 79.920000000000002,
                            Name = "Kelaniya Depot",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("WasteGlassApi.Models.CollectionRecord", b =>
                {
                    b.HasOne("WasteGlassApi.Models.Supplier", "Supplier")
                        .WithMany("CollectionRecords")
                        .HasForeignKey("SupplierId")
                        .HasPrincipalKey("BarcodeRef")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WasteGlassApi.Models.Supplier", b =>
                {
                    b.Navigation("CollectionRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
